#ifndef EUPHSTANDARDCOLOUR_HPP
#define EUPHSTANDARDCOLOUR_HPP
#include <map>
#include <array>
#include <cstdint>
#include <string_view>
#include <Euphemy/Media/Image/EuphPixelFormat.hpp>
#include <Euphemy/Config/EuphLib.hpp>
namespace Euph {
namespace Media {
namespace Image {

enum class StandardColourEnum : uint8_t {
	aliceblue,
	antiquewhite,
	aqua,
	aquamarine,
	azure,
	beige,
	bisque,
	black,
	blanchedalmond,
	blue,
	blueviolet,
	brown,
	burlywood,
	cadetblue,
	chartreuse,
	chocolate,
	coral,
	cornflowerblue,
	cornsilk,
	crimson,
	cyan,
	darkblue,
	darkcyan,
	darkgoldenrod,
	darkgray,
	darkgreen,
	darkkhaki,
	darkmagenta,
	darkolivegreen,
	darkorange,
	darkorchid,
	darkred,
	darksalmon,
	darkseagreen,
	darkslateblue,
	darkslategray,
	darkturquoise,
	darkviolet,
	deeppink,
	deepskyblue,
	dimgray,
	dodgerblue,
	firebrick,
	floralwhite,
	forestgreen,
	fuchsia,
	gainsboro,
	ghostwhite,
	gold,
	goldenrod,
	gray,
	green,
	greenyellow,
	honeydew,
	hotpink,
	indianred,
	indigo,
	ivory,
	khaki,
	lavender,
	lavenderblush,
	lawngreen,
	lemonchiffon,
	lightblue,
	lightcoral,
	lightcyan,
	lightgoldenrodyellow,
	lightgray,
	lightgreen,
	lightpink,
	lightsalmon,
	lightseagreen,
	lightskyblue,
	lightslategray,
	lightsteelblue,
	lightyellow,
	lime,
	limegreen,
	linen,
	magenta,
	maroon,
	mediumaquamarine,
	mediumblue,
	mediumorchid,
	mediumpurple,
	mediumseagreen,
	mediumslateblue,
	mediumspringgreen,
	mediumturquoise,
	mediumvioletred,
	midnightblue,
	mintcream,
	mistyrose,
	moccasin,
	navajowhite,
	navy,
	oldlace,
	olive,
	olivedrab,
	orange,
	orangered,
	orchid,
	palegoldenrod,
	palegreen,
	paleturquoise,
	palevioletred,
	papayawhip,
	peachpuff,
	peru,
	pink,
	plum,
	powderblue,
	purple,
	rebeccapurple,
	red,
	rosybrown,
	royalblue,
	saddlebrown,
	salmon,
	sandybrown,
	seagreen,
	seashell,
	sienna,
	silver,
	skyblue,
	slateblue,
	slategray,
	snow,
	springgreen,
	steelblue,
	tan,
	teal,
	thistle,
	tomato,
	turquoise,
	violet,
	wheat,
	white,
	whitesmoke,
	yellow,
	yellowgreen
};
typedef std::map<std::string, StandardColourEnum, std::less<>> StringToStandardColourEnumMap;
const PixelRGB_U8& MH_EUPH_API getStandardColour(StandardColourEnum index);
const PixelRGB_U8& MH_EUPH_API getStandardColour(const std::string_view name);
const StringToStandardColourEnumMap& MH_EUPH_API getAllValidColorNames();

}
}
}
#endif // EUPHSTANDARDCOLOUR_HPP
