#include "EuphStandardColour.hpp"
namespace Euph {
namespace Media {
namespace Image {

typedef std::array<PixelRGB_U8, static_cast<std::size_t>(StandardColourEnum::yellowgreen)+1> StandardColourMap;
static const StringToStandardColourEnumMap NamedColours = {
	{ "aliceblue", StandardColourEnum::aliceblue},
	{ "antiquewhite", StandardColourEnum::antiquewhite},
	{ "aqua", StandardColourEnum::aqua},
	{ "aquamarine", StandardColourEnum::aquamarine},
	{ "azure", StandardColourEnum::azure},
	{ "beige", StandardColourEnum::beige},
	{ "bisque", StandardColourEnum::bisque},
	{ "black", StandardColourEnum::black},
	{ "blanchedalmond", StandardColourEnum::blanchedalmond},
	{ "blue", StandardColourEnum::blue},
	{ "blueviolet", StandardColourEnum::blueviolet},
	{ "brown", StandardColourEnum::brown},
	{ "burlywood", StandardColourEnum::burlywood},
	{ "cadetblue", StandardColourEnum::cadetblue},
	{ "chartreuse", StandardColourEnum::chartreuse},
	{ "chocolate", StandardColourEnum::chocolate},
	{ "coral", StandardColourEnum::coral},
	{ "cornflowerblue", StandardColourEnum::cornflowerblue},
	{ "cornsilk", StandardColourEnum::cornsilk},
	{ "crimson", StandardColourEnum::crimson},
	{ "cyan", StandardColourEnum::cyan},
	{ "darkblue", StandardColourEnum::darkblue},
	{ "darkcyan", StandardColourEnum::darkcyan},
	{ "darkgoldenrod", StandardColourEnum::darkgoldenrod},
	{ "darkgray", StandardColourEnum::darkgray},
	{ "darkgreen", StandardColourEnum::darkgreen},
	{ "darkkhaki", StandardColourEnum::darkkhaki},
	{ "darkmagenta", StandardColourEnum::darkmagenta},
	{ "darkolivegreen", StandardColourEnum::darkolivegreen},
	{ "darkorange", StandardColourEnum::darkorange},
	{ "darkorchid", StandardColourEnum::darkorchid},
	{ "darkred", StandardColourEnum::darkred},
	{ "darksalmon", StandardColourEnum::darksalmon},
	{ "darkseagreen", StandardColourEnum::darkseagreen},
	{ "darkslateblue", StandardColourEnum::darkslateblue},
	{ "darkslategray", StandardColourEnum::darkslategray},
	{ "darkturquoise", StandardColourEnum::darkturquoise},
	{ "darkviolet", StandardColourEnum::darkviolet},
	{ "deeppink", StandardColourEnum::deeppink},
	{ "deepskyblue", StandardColourEnum::deepskyblue},
	{ "dimgray", StandardColourEnum::dimgray},
	{ "dodgerblue", StandardColourEnum::dodgerblue},
	{ "firebrick", StandardColourEnum::firebrick},
	{ "floralwhite", StandardColourEnum::floralwhite},
	{ "forestgreen", StandardColourEnum::forestgreen},
	{ "fuchsia", StandardColourEnum::fuchsia},
	{ "gainsboro", StandardColourEnum::gainsboro},
	{ "ghostwhite", StandardColourEnum::ghostwhite},
	{ "gold", StandardColourEnum::gold},
	{ "goldenrod", StandardColourEnum::goldenrod},
	{ "gray", StandardColourEnum::gray},
	{ "green", StandardColourEnum::green},
	{ "greenyellow", StandardColourEnum::greenyellow},
	{ "honeydew", StandardColourEnum::honeydew},
	{ "hotpink", StandardColourEnum::hotpink},
	{ "indianred", StandardColourEnum::indianred},
	{ "indigo", StandardColourEnum::indigo},
	{ "ivory", StandardColourEnum::ivory},
	{ "khaki", StandardColourEnum::khaki},
	{ "lavender", StandardColourEnum::lavender},
	{ "lavenderblush", StandardColourEnum::lavenderblush},
	{ "lawngreen", StandardColourEnum::lawngreen},
	{ "lemonchiffon", StandardColourEnum::lemonchiffon},
	{ "lightblue", StandardColourEnum::lightblue},
	{ "lightcoral", StandardColourEnum::lightcoral},
	{ "lightcyan", StandardColourEnum::lightcyan},
	{ "lightgoldenrodyellow", StandardColourEnum::lightgoldenrodyellow},
	{ "lightgray", StandardColourEnum::lightgray},
	{ "lightgreen", StandardColourEnum::lightgreen},
	{ "lightpink", StandardColourEnum::lightpink},
	{ "lightsalmon", StandardColourEnum::lightsalmon},
	{ "lightseagreen", StandardColourEnum::lightseagreen},
	{ "lightskyblue", StandardColourEnum::lightskyblue},
	{ "lightslategray", StandardColourEnum::lightslategray},
	{ "lightsteelblue", StandardColourEnum::lightsteelblue},
	{ "lightyellow", StandardColourEnum::lightyellow},
	{ "lime", StandardColourEnum::lime},
	{ "limegreen", StandardColourEnum::limegreen},
	{ "linen", StandardColourEnum::linen},
	{ "magenta", StandardColourEnum::magenta},
	{ "maroon", StandardColourEnum::maroon},
	{ "mediumaquamarine", StandardColourEnum::mediumaquamarine},
	{ "mediumblue", StandardColourEnum::mediumblue},
	{ "mediumorchid", StandardColourEnum::mediumorchid},
	{ "mediumpurple", StandardColourEnum::mediumpurple},
	{ "mediumseagreen", StandardColourEnum::mediumseagreen},
	{ "mediumslateblue", StandardColourEnum::mediumslateblue},
	{ "mediumspringgreen", StandardColourEnum::mediumspringgreen},
	{ "mediumturquoise", StandardColourEnum::mediumturquoise},
	{ "mediumvioletred", StandardColourEnum::mediumvioletred},
	{ "midnightblue", StandardColourEnum::midnightblue},
	{ "mintcream", StandardColourEnum::mintcream},
	{ "mistyrose", StandardColourEnum::mistyrose},
	{ "moccasin", StandardColourEnum::moccasin},
	{ "navajowhite", StandardColourEnum::navajowhite},
	{ "navy", StandardColourEnum::navy},
	{ "oldlace", StandardColourEnum::oldlace},
	{ "olive", StandardColourEnum::olive},
	{ "olivedrab", StandardColourEnum::olivedrab},
	{ "orange", StandardColourEnum::orange},
	{ "orangered", StandardColourEnum::orangered},
	{ "orchid", StandardColourEnum::orchid},
	{ "palegoldenrod", StandardColourEnum::palegoldenrod},
	{ "palegreen", StandardColourEnum::palegreen},
	{ "paleturquoise", StandardColourEnum::paleturquoise},
	{ "palevioletred", StandardColourEnum::palevioletred},
	{ "papayawhip", StandardColourEnum::papayawhip},
	{ "peachpuff", StandardColourEnum::peachpuff},
	{ "peru", StandardColourEnum::peru},
	{ "pink", StandardColourEnum::pink},
	{ "plum", StandardColourEnum::plum},
	{ "powderblue", StandardColourEnum::powderblue},
	{ "purple", StandardColourEnum::purple},
	{ "rebeccapurple", StandardColourEnum::rebeccapurple},
	{ "red", StandardColourEnum::red},
	{ "rosybrown", StandardColourEnum::rosybrown},
	{ "royalblue", StandardColourEnum::royalblue},
	{ "saddlebrown", StandardColourEnum::saddlebrown},
	{ "salmon", StandardColourEnum::salmon},
	{ "sandybrown", StandardColourEnum::sandybrown},
	{ "seagreen", StandardColourEnum::seagreen},
	{ "seashell", StandardColourEnum::seashell},
	{ "sienna", StandardColourEnum::sienna},
	{ "silver", StandardColourEnum::silver},
	{ "skyblue", StandardColourEnum::skyblue},
	{ "slateblue", StandardColourEnum::slateblue},
	{ "slategray", StandardColourEnum::slategray},
	{ "snow", StandardColourEnum::snow},
	{ "springgreen", StandardColourEnum::springgreen},
	{ "steelblue", StandardColourEnum::steelblue},
	{ "tan", StandardColourEnum::tan},
	{ "teal", StandardColourEnum::teal},
	{ "thistle", StandardColourEnum::thistle},
	{ "tomato", StandardColourEnum::tomato},
	{ "turquoise", StandardColourEnum::turquoise},
	{ "violet", StandardColourEnum::violet},
	{ "wheat", StandardColourEnum::wheat},
	{ "white", StandardColourEnum::white},
	{ "whitesmoke", StandardColourEnum::whitesmoke},
	{ "yellow", StandardColourEnum::yellow},
	{ "yellowgreen", StandardColourEnum::yellowgreen},
};
static const StandardColourMap NamedColourMap = {
	PixelRGB_U8{ .r = 240 , .g = 248 , .b = 255 },
	PixelRGB_U8{ .r = 250 , .g = 235 , .b = 215 },
	PixelRGB_U8{ .r = 0 , .g = 255 , .b = 255 },
	PixelRGB_U8{ .r = 127 , .g = 255 , .b = 212 },
	PixelRGB_U8{ .r = 240 , .g = 255 , .b = 255 },
	PixelRGB_U8{ .r = 245 , .g = 245 , .b = 220 },
	PixelRGB_U8{ .r = 255 , .g = 228 , .b = 196 },
	PixelRGB_U8{ .r = 0 , .g = 0 , .b = 0 },
	PixelRGB_U8{ .r = 255 , .g = 235 , .b = 205 },
	PixelRGB_U8{ .r = 0 , .g = 0 , .b = 255 },
	PixelRGB_U8{ .r = 138 , .g = 43 , .b = 226 },
	PixelRGB_U8{ .r = 165 , .g = 42 , .b = 42 },
	PixelRGB_U8{ .r = 222 , .g = 184 , .b = 135 },
	PixelRGB_U8{ .r = 95 , .g = 158 , .b = 160 },
	PixelRGB_U8{ .r = 127 , .g = 255 , .b = 0 },
	PixelRGB_U8{ .r = 210 , .g = 105 , .b = 30 },
	PixelRGB_U8{ .r = 255 , .g = 127 , .b = 80 },
	PixelRGB_U8{ .r = 100 , .g = 149 , .b = 237 },
	PixelRGB_U8{ .r = 255 , .g = 248 , .b = 220 },
	PixelRGB_U8{ .r = 220 , .g = 20 , .b = 60 },
	PixelRGB_U8{ .r = 0 , .g = 255 , .b = 255 },
	PixelRGB_U8{ .r = 0 , .g = 0 , .b = 139 },
	PixelRGB_U8{ .r = 0 , .g = 139 , .b = 139 },
	PixelRGB_U8{ .r = 184 , .g = 134 , .b = 11 },
	PixelRGB_U8{ .r = 169 , .g = 169 , .b = 169 },
	PixelRGB_U8{ .r = 0 , .g = 100 , .b = 0 },
	PixelRGB_U8{ .r = 189 , .g = 183 , .b = 107 },
	PixelRGB_U8{ .r = 139 , .g = 0 , .b = 139 },
	PixelRGB_U8{ .r = 85 , .g = 107 , .b = 47 },
	PixelRGB_U8{ .r = 255 , .g = 140 , .b = 0 },
	PixelRGB_U8{ .r = 153 , .g = 50 , .b = 204 },
	PixelRGB_U8{ .r = 139 , .g = 0 , .b = 0 },
	PixelRGB_U8{ .r = 233 , .g = 150 , .b = 122 },
	PixelRGB_U8{ .r = 143 , .g = 188 , .b = 139 },
	PixelRGB_U8{ .r = 72 , .g = 61 , .b = 139 },
	PixelRGB_U8{ .r = 47 , .g = 79 , .b = 79 },
	PixelRGB_U8{ .r = 0 , .g = 206 , .b = 209 },
	PixelRGB_U8{ .r = 148 , .g = 0 , .b = 211 },
	PixelRGB_U8{ .r = 255 , .g = 20 , .b = 147 },
	PixelRGB_U8{ .r = 0 , .g = 191 , .b = 255 },
	PixelRGB_U8{ .r = 105 , .g = 105 , .b = 105 },
	PixelRGB_U8{ .r = 30 , .g = 144 , .b = 255 },
	PixelRGB_U8{ .r = 178 , .g = 34 , .b = 34 },
	PixelRGB_U8{ .r = 255 , .g = 250 , .b = 240 },
	PixelRGB_U8{ .r = 34 , .g = 139 , .b = 34 },
	PixelRGB_U8{ .r = 255 , .g = 0 , .b = 255 },
	PixelRGB_U8{ .r = 220 , .g = 220 , .b = 220 },
	PixelRGB_U8{ .r = 248 , .g = 248 , .b = 255 },
	PixelRGB_U8{ .r = 255 , .g = 215 , .b = 0 },
	PixelRGB_U8{ .r = 218 , .g = 165 , .b = 32 },
	PixelRGB_U8{ .r = 128 , .g = 128 , .b = 128 },
	PixelRGB_U8{ .r = 0 , .g = 128 , .b = 0 },
	PixelRGB_U8{ .r = 173 , .g = 255 , .b = 47 },
	PixelRGB_U8{ .r = 240 , .g = 255 , .b = 240 },
	PixelRGB_U8{ .r = 255 , .g = 105 , .b = 180 },
	PixelRGB_U8{ .r = 205 , .g = 92 , .b = 92 },
	PixelRGB_U8{ .r = 75 , .g = 0 , .b = 130 },
	PixelRGB_U8{ .r = 255 , .g = 255 , .b = 240 },
	PixelRGB_U8{ .r = 240 , .g = 230 , .b = 140 },
	PixelRGB_U8{ .r = 230 , .g = 230 , .b = 250 },
	PixelRGB_U8{ .r = 255 , .g = 240 , .b = 245 },
	PixelRGB_U8{ .r = 124 , .g = 252 , .b = 0 },
	PixelRGB_U8{ .r = 255 , .g = 250 , .b = 205 },
	PixelRGB_U8{ .r = 173 , .g = 216 , .b = 230 },
	PixelRGB_U8{ .r = 240 , .g = 128 , .b = 128 },
	PixelRGB_U8{ .r = 224 , .g = 255 , .b = 255 },
	PixelRGB_U8{ .r = 250 , .g = 250 , .b = 210 },
	PixelRGB_U8{ .r = 211 , .g = 211 , .b = 211 },
	PixelRGB_U8{ .r = 144 , .g = 238 , .b = 144 },
	PixelRGB_U8{ .r = 255 , .g = 182 , .b = 193 },
	PixelRGB_U8{ .r = 255 , .g = 160 , .b = 122 },
	PixelRGB_U8{ .r = 32 , .g = 178 , .b = 170 },
	PixelRGB_U8{ .r = 135 , .g = 206 , .b = 250 },
	PixelRGB_U8{ .r = 119 , .g = 136 , .b = 153 },
	PixelRGB_U8{ .r = 176 , .g = 196 , .b = 222 },
	PixelRGB_U8{ .r = 255 , .g = 255 , .b = 224 },
	PixelRGB_U8{ .r = 0 , .g = 255 , .b = 0 },
	PixelRGB_U8{ .r = 50 , .g = 205 , .b = 50 },
	PixelRGB_U8{ .r = 250 , .g = 240 , .b = 230 },
	PixelRGB_U8{ .r = 255 , .g = 0 , .b = 255 },
	PixelRGB_U8{ .r = 128 , .g = 0 , .b = 0 },
	PixelRGB_U8{ .r = 102 , .g = 205 , .b = 170 },
	PixelRGB_U8{ .r = 0 , .g = 0 , .b = 205 },
	PixelRGB_U8{ .r = 186 , .g = 85 , .b = 211 },
	PixelRGB_U8{ .r = 147 , .g = 112 , .b = 219 },
	PixelRGB_U8{ .r = 60 , .g = 179 , .b = 113 },
	PixelRGB_U8{ .r = 123 , .g = 104 , .b = 238 },
	PixelRGB_U8{ .r = 0 , .g = 250 , .b = 154 },
	PixelRGB_U8{ .r = 72 , .g = 209 , .b = 204 },
	PixelRGB_U8{ .r = 199 , .g = 21 , .b = 133 },
	PixelRGB_U8{ .r = 25 , .g = 25 , .b = 112 },
	PixelRGB_U8{ .r = 245 , .g = 255 , .b = 250 },
	PixelRGB_U8{ .r = 255 , .g = 228 , .b = 225 },
	PixelRGB_U8{ .r = 255 , .g = 228 , .b = 181 },
	PixelRGB_U8{ .r = 255 , .g = 222 , .b = 173 },
	PixelRGB_U8{ .r = 0 , .g = 0 , .b = 128 },
	PixelRGB_U8{ .r = 253 , .g = 245 , .b = 230 },
	PixelRGB_U8{ .r = 128 , .g = 128 , .b = 0 },
	PixelRGB_U8{ .r = 107 , .g = 142 , .b = 35 },
	PixelRGB_U8{ .r = 255 , .g = 165 , .b = 0 },
	PixelRGB_U8{ .r = 255 , .g = 69 , .b = 0 },
	PixelRGB_U8{ .r = 218 , .g = 112 , .b = 214 },
	PixelRGB_U8{ .r = 238 , .g = 232 , .b = 170 },
	PixelRGB_U8{ .r = 152 , .g = 251 , .b = 152 },
	PixelRGB_U8{ .r = 175 , .g = 238 , .b = 238 },
	PixelRGB_U8{ .r = 219 , .g = 112 , .b = 147 },
	PixelRGB_U8{ .r = 255 , .g = 239 , .b = 213 },
	PixelRGB_U8{ .r = 255 , .g = 218 , .b = 185 },
	PixelRGB_U8{ .r = 205 , .g = 133 , .b = 63 },
	PixelRGB_U8{ .r = 255 , .g = 192 , .b = 203 },
	PixelRGB_U8{ .r = 221 , .g = 160 , .b = 221 },
	PixelRGB_U8{ .r = 176 , .g = 224 , .b = 230 },
	PixelRGB_U8{ .r = 128 , .g = 0 , .b = 128 },
	PixelRGB_U8{ .r = 102 , .g = 51 , .b = 153 },
	PixelRGB_U8{ .r = 255 , .g = 0 , .b = 0 },
	PixelRGB_U8{ .r = 188 , .g = 143 , .b = 143 },
	PixelRGB_U8{ .r = 65 , .g = 105 , .b = 225 },
	PixelRGB_U8{ .r = 139 , .g = 69 , .b = 19 },
	PixelRGB_U8{ .r = 250 , .g = 128 , .b = 114 },
	PixelRGB_U8{ .r = 244 , .g = 164 , .b = 96 },
	PixelRGB_U8{ .r = 46 , .g = 139 , .b = 87 },
	PixelRGB_U8{ .r = 255 , .g = 245 , .b = 238 },
	PixelRGB_U8{ .r = 160 , .g = 82 , .b = 45 },
	PixelRGB_U8{ .r = 192 , .g = 192 , .b = 192 },
	PixelRGB_U8{ .r = 135 , .g = 206 , .b = 235 },
	PixelRGB_U8{ .r = 106 , .g = 90 , .b = 205 },
	PixelRGB_U8{ .r = 112 , .g = 128 , .b = 144 },
	PixelRGB_U8{ .r = 255 , .g = 250 , .b = 250 },
	PixelRGB_U8{ .r = 0 , .g = 255 , .b = 127 },
	PixelRGB_U8{ .r = 70 , .g = 130 , .b = 180 },
	PixelRGB_U8{ .r = 210 , .g = 180 , .b = 140 },
	PixelRGB_U8{ .r = 0 , .g = 128 , .b = 128 },
	PixelRGB_U8{ .r = 216 , .g = 191 , .b = 216 },
	PixelRGB_U8{ .r = 255 , .g = 99 , .b = 71 },
	PixelRGB_U8{ .r = 64 , .g = 224 , .b = 208 },
	PixelRGB_U8{ .r = 238 , .g = 130 , .b = 238 },
	PixelRGB_U8{ .r = 245 , .g = 222 , .b = 179 },
	PixelRGB_U8{ .r = 255 , .g = 255 , .b = 255 },
	PixelRGB_U8{ .r = 245 , .g = 245 , .b = 245 },
	PixelRGB_U8{ .r = 255 , .g = 255 , .b = 0 },
	PixelRGB_U8{ .r = 154 , .g = 205 , .b = 50 }
};

const PixelRGB_U8& getStandardColour(StandardColourEnum index)
{
	return NamedColourMap[static_cast<uint8_t>(index)];
}

const PixelRGB_U8& getStandardColour(const std::string_view name)
{
	auto index = NamedColours.find(name);
	if(index != std::end(NamedColours)) return getStandardColour(index->second);
	else return getStandardColour(StandardColourEnum::black);
}

const StringToStandardColourEnumMap& getAllValidColorNames()
{
	return NamedColours;
}

}
}
}
