#ifndef ELVIDPOOL_H
#define ELVIDPOOL_H
#include <memory>
#include <atomic>
#include <vector>
#include <mutex>
namespace Elv {
namespace Util {

/**
 * @brief A thread-safe pool for managing and recycling unique identifiers.
 *
 * This class dispenses unique sequential identifiers of type @p T. It prioritizes
 * recycling previously released IDs stored in an internal free-list before
 * generating brand-new sequential IDs.
 *
 * @tparam T The underlying integer type used for the Identifier (e.g., uint32_t, uint64_t).
 * @tparam Allocator The allocator type used for the internal tracking collection.
 */
template <typename T, typename Allocator = std::allocator<T>>
class IdPool {
public:
	/// @brief Convenient alias for the identifier type.
	typedef T Id;

	/// @brief Container type used for managing released IDs.
	typedef std::vector<T, Allocator> Freelist;

private:
	Id lastId;                  ///< The highest ID value generated so far.
	Freelist freelist;          ///< Collection of recycled IDs ready for reuse.
	mutable std::mutex mutex;   ///< Mutex protecting pool access across threads.

public:
	/**
	 * @brief Constructs an empty ID pool.
	 * @param alloc The allocator instance to use for internal storage.
	 */
	explicit IdPool(const Allocator& alloc = Allocator())
		: lastId(static_cast<T>(0)), freelist(alloc) {}

	/**
	 * @brief Constructs an empty ID pool.
	 * @param freeListInitialSize The initial reserved pool size for the freelist, to avoid reallocations initially.
	 * @param alloc The allocator instance to use for internal storage.
	 */
	explicit IdPool(size_t freeListInitialSize, const Allocator& alloc = Allocator())
		: lastId(static_cast<T>(0)), freelist(alloc) {
		freelist.reserve(freeListInitialSize);
	}

	// Deleted copy operations to prevent accidental duplication of thread synchronization primitives.
	IdPool(const IdPool& cpy) = delete;
	IdPool& operator=(const IdPool& cpy) = delete;

	/**
	 * @brief Move constructor.
	 * @param mov The pool instance to move from.
	 */
	IdPool(IdPool&& mov) noexcept = default;

	/**
	 * @brief Move assignment operator.
	 * @param mov The pool instance to move from.
	 * @return A reference to this instance.
	 */
	IdPool& operator=(IdPool&& mov) noexcept = default;

	/**
	 * @brief Retrieves the highest single ID value generated by the pool so far.
	 * @note This does not reflect IDs currently sitting inside the free-list.
	 * @return The maximum raw ID value generated.
	 */
	T getLastId() const noexcept {
		std::lock_guard<std::mutex> lock(mutex);
		return lastId;
	}

	/**
	 * @brief Returns an ID back to the pool for future recycling.
	 *
	 * @param toFree The identifier to release back into the pool.
	 *
	 * @warning Releasing the same ID more than once (double-release) results in
	 *          undefined behavior! It is highly recommended to wrap acquired IDs
	 *          in RAII-driven resource management wrappers to ensure unique,
	 *          single-time releases.
	 */
	void release(T toFree) {
		std::lock_guard<std::mutex> lock(mutex);
		freelist.push_back(toFree);
	}

	/**
	 * @brief Acquires a unique ID from the pool.
	 *
	 * This method will pop and reuse an ID from the internal free-list if one is
	 * available. If the free-list is empty, it increments the internal counter
	 * and returns a completely new sequential ID.
	 *
	 * @return A unique identifier of type @p T.
	 */
	T acquireId() {
		std::lock_guard<std::mutex> lock(mutex);
		if (freelist.size()) {
			T back = freelist.back();
			freelist.pop_back();
			return back;
		} else {
			return ++lastId;
		}
	}
};

}
}
#endif // ELVIDPOOL_H
