#ifndef ELVIDPOOL_H
#define ELVIDPOOL_H
#include <memory>
#include <atomic>
#include <vector>
#include <mutex>
namespace Elv {
namespace Util {

/**
 * @brief A thread-safe pool for managing and recycling unique identifiers.
 *
 * This class dispenses unique sequential identifiers of type @p T. It prioritizes
 * recycling previously released IDs stored in an internal free-list before
 * generating brand-new sequential IDs.
 *
 * @tparam T The underlying integer type used for the Identifier (e.g., uint32_t, uint64_t).
 * @tparam Allocator The allocator type used for the internal tracking collection.
 */
template <typename T, typename Allocator = std::allocator<T>>
class IdPool {
public:
	/// @brief Convenient alias for the identifier type.
	typedef T Id;

	/// @brief Container type used for managing released IDs.
	typedef std::vector<T, Allocator> Freelist;

private:
	Id lastId;                  ///< The highest ID value generated so far.
	Freelist freelist;          ///< Collection of recycled IDs ready for reuse.
	mutable std::mutex mutex;   ///< Mutex protecting pool access across threads.

public:
	/**
	 * @brief Constructs an empty ID pool.
	 * @param alloc The allocator instance to use for internal storage.
	 */
	explicit IdPool(const Allocator& alloc = Allocator())
		: lastId(static_cast<T>(0)), freelist(alloc) {}

	/**
	 * @brief Constructs an empty ID pool.
	 * @param freeListInitialSize The initial reserved pool size for the freelist, to avoid reallocations initially.
	 * @param alloc The allocator instance to use for internal storage.
	 */
	explicit IdPool(size_t freeListInitialSize, const Allocator& alloc = Allocator())
		: lastId(static_cast<T>(0)), freelist(alloc) {
		freelist.reserve(freeListInitialSize);
	}

	// Deleted copy operations to prevent accidental duplication of thread synchronization primitives.
	IdPool(const IdPool& cpy) = delete;
	IdPool& operator=(const IdPool& cpy) = delete;

	/**
	 * @brief Move constructor.
	 * @param mov The pool instance to move from.
	 */
	IdPool(IdPool&& mov) noexcept = default;

	/**
	 * @brief Move assignment operator.
	 * @param mov The pool instance to move from.
	 * @return A reference to this instance.
	 */
	IdPool& operator=(IdPool&& mov) noexcept = default;

	/**
	 * @brief Retrieves the highest single ID value generated by the pool so far.
	 * @note This does not reflect IDs currently sitting inside the free-list.
	 * @return The maximum raw ID value generated.
	 */
	[[nodiscard]] T getLastId() const noexcept {
		std::lock_guard<std::mutex> lock(mutex);
		return lastId;
	}

	/**
	 * @brief Returns an ID back to the pool for future recycling.
	 *
	 * @param toFree The identifier to release back into the pool.
	 *
	 * @warning Releasing the same ID more than once (double-release) results in
	 *          undefined behavior! It is highly recommended to wrap acquired IDs
	 *          in RAII-driven resource management wrappers to ensure unique,
	 *          single-time releases.
	 */
	void release(T toFree) {
		std::lock_guard<std::mutex> lock(mutex);
		freelist.push_back(toFree);
	}

	/**
	 * @brief Returns a batch of IDs back to the pool for future recycling.
	 *
	 * Efficiently processes multiple IDs under a single lock acquisition phase.
	 *
	 * @param ids A pointer to the continuous array containing IDs to release.
	 * @param number The number of identifiers present in the @p ids array.
	 *
	 * @warning Just like single-release, providing duplicated or already-freed IDs
	 *          within this block will result in undefined behavior.
	 */
	void releaseMultiple(const T* ids, size_t number) {
		if (number == 0) return; // Quick escape if empty batch

		std::lock_guard<std::mutex> lock(mutex);

		// Check if appending these IDs will exceed current capacity
		if (freelist.size() + number > freelist.capacity()) {
			freelist.reserve(freelist.size() + number);
		}

		for (size_t i = 0; i < number; ++i) {
			freelist.push_back(ids[i]);
		}
	}

	/**
	 * @brief Acquires a unique ID from the pool.
	 *
	 * This method will pop and reuse an ID from the internal free-list if one is
	 * available. If the free-list is empty, it increments the internal counter
	 * and returns a completely new sequential ID.
	 *
	 * @return A unique identifier of type @p T.
	 */
	[[nodiscard]] T acquireId() {
		std::lock_guard<std::mutex> lock(mutex);
		if (freelist.size()) {
			T back = freelist.back();
			freelist.pop_back();
			return back;
		} else {
			return ++lastId;
		}
	}

	/**
	 * @brief Acquires a batch of unique IDs from the pool simultaneously.
	 *
	 * Minimizes lock contention by acquiring IDs in bulk. It will exhaust available
	 * recycled elements from the internal free-list before generating sequential fresh IDs.
	 *
	 * @param ids A pointer to an allocated array large enough to hold @p number elements.
	 * @param number The total number of unique identifiers requested.
	 */
	void acquireMultiple(T* ids, size_t number) {
		if (number == 0) return;

		std::lock_guard<std::mutex> lock(mutex);

		size_t fromFreelist = std::min(number, freelist.size());
		size_t i = 0;

		for (; i < fromFreelist; ++i) {
			ids[i] = freelist.back();
			freelist.pop_back();
		}

		for (; i < number; ++i) {
			ids[i] = ++lastId;
		}
	}

	/**
	 * @brief Acquires a batch of unique IDs and streams them directly into a callback function.
	 *
	 * Minimizes lock contention by acquiring IDs in bulk. Instead of writing out to a raw
	 * array buffer, this method invokes the provided callback function for each acquired ID.
	 *
	 * @tparam Func A callable type that accepts an ID of type @p T as its argument.
	 * @param number The total number of unique identifiers requested.
	 * @param func The callback function or lambda expression to invoke for each generated ID.
	 */
	template <typename Func>
	void acquireMultiple(size_t number, Func&& func) {
		static_assert(std::is_invocable_v<Func, T>,
					  "The provided callback must accept an argument compatible with type T (IdPool::Id).");

		if (number == 0) return;

		std::lock_guard<std::mutex> lock(mutex);

		size_t fromFreelist = std::min(number, freelist.size());
		size_t i = 0;

		// 1. Stream recycled elements out of the freelist
		for (; i < fromFreelist; ++i) {
			T back = freelist.back();
			freelist.pop_back();
			func(back);
		}

		// 2. Stream freshly generated IDs
		for (; i < number; ++i) {
			func(++lastId);
		}
	}
};

}
}
#endif // ELVIDPOOL_H
