#ifndef EUPHRESAMPLER_HPP
#define EUPHRESAMPLER_HPP

/**
 * @file EuphResampler.hpp
 * @brief libsamplerate-backed resampler wrappers for simple, streaming, and callback-driven use.
 */

#include <Euphemy/Config/EuphLib.hpp>
#include <Euphemy/Media/Audio/EuphAudioIterator.hpp>
#include <Elvavena/Io/ElvIoDevice.hpp>
#include <memory>
#include <samplerate.h>
namespace Euph {
namespace Media {
namespace Audio {

/**
 * @brief Resampling converter quality/performance modes.
 */
enum class ResampleType : int {
	/** @brief Highest quality sinc-based conversion. */
	SINC_BEST_QUALITY = 0,
	/** @brief Medium quality sinc-based conversion. */
	SINC_MEDIUM_QUALITY = 1,
	/** @brief Fastest sinc-based conversion. */
	SINC_FASTEST = 2,
	/** @brief Zero-order hold conversion. */
	ZERO_ORDER_HOLD = 3,
	/** @brief Linear interpolation conversion. */
	LINEAR = 4
};

/**
 * @brief RAII deleter for libsamplerate state objects.
 */
struct MH_EUPH_API SrcStateDeleter {
	/**
	 * @brief Deletes a libsamplerate state.
	 * @param state State pointer created by libsamplerate or nullptr.
	 */
	void operator( )( SRC_STATE *state ) const;
};

DEFINE_CLASS_WITH_POLYMORPHIC_ALLOCATOR(SimpleResampler)
/**
 * @brief Thin wrapper over `src_simple` using a directly-owned `SRC_DATA`.
 */
class MH_EUPH_API SimpleResampler {
private:
	mutable SRC_DATA handle;
	SimpleResampler( const SimpleResampler &cpy ) = delete;
	SimpleResampler& operator=( const SimpleResampler &cpy ) = delete;
public:
	/** @brief Destructor. */
	~SimpleResampler( );
	/** @brief Creates a zero-initialized resampler descriptor. */
	SimpleResampler( );
	/**
	 * @brief Creates a resampler descriptor with all main fields set.
	 * @param dataIn Input interleaved float buffer.
	 * @param inputFrames Number of available input frames.
	 * @param dataOut Output interleaved float buffer.
	 * @param outputFrames Maximum number of output frames.
	 * @param src_ratio Input-to-output sample-rate ratio.
	 */
	explicit SimpleResampler( float *dataIn, FrameCount inputFrames, float *dataOut,
					FrameCount outputFrames, double src_ratio );
	/** @brief Move constructor. */
	SimpleResampler( SimpleResampler &&mov );
	/** @brief Move assignment. */
	SimpleResampler& operator=( SimpleResampler &&mov );

	/**
	 * @brief Runs one-shot conversion through `src_simple`.
	 * @param resamplerType Converter mode.
	 * @param channels Interleaved channel count.
	 * @return libsamplerate error code (`0` on success).
	 */
	int resample( ResampleType resamplerType, ChannelCount channels ) const;
	/** @brief Returns the input data pointer currently stored in `SRC_DATA`. */
	const float *getDataIn( ) const;
	/** @brief Returns the output data pointer currently stored in `SRC_DATA`. */
	float *getDataOut( ) const;
	/** @brief Returns the input frame count currently stored in `SRC_DATA`. */
	FrameCount getInputFrames( ) const;
	/** @brief Returns the number of input frames consumed by the last process call. */
	FrameCount getInputFramesUsed( ) const;
	/** @brief Returns the output frame capacity currently stored in `SRC_DATA`. */
	FrameCount getOutputFrames( ) const;
	/** @brief Returns the number of output frames generated by the last process call. */
	FrameCount getOutputFramesGenerated( ) const;
	/** @brief Returns the current resampling ratio. */
	double getRatio( ) const;
	/** @brief Returns the end-of-input flag. */
	bool getEndOfInput( ) const;
	/** @brief Sets the input data pointer. */
	void setDataIn( const float *set_to ) const;
	/** @brief Sets the output data pointer. */
	void setDataOut( float *set_to ) const;
	/** @brief Sets the input frame count. */
	void setInputFrames( FrameCount set_to ) const;
	/** @brief Sets the output frame capacity. */
	void setOutputFrames( FrameCount set_to ) const;
	/** @brief Sets the resampling ratio. */
	void setRatio( double set_to ) const;
	/** @brief Sets the end-of-input flag. */
	void setEndOfInput( bool set_to ) const;
	/**
	 * @brief Sets the primary conversion parameters in one call.
	 * @param data_in Input interleaved float buffer.
	 * @param data_out Output interleaved float buffer.
	 * @param input_frames Number of available input frames.
	 * @param output_frames Maximum number of output frames.
	 * @param ratio Input-to-output sample-rate ratio.
	 */
	void set( const float *data_in, float *data_out, FrameCount input_frames,
			 FrameCount output_frames, double ratio ) const;
};

DEFINE_CLASS_WITH_POLYMORPHIC_ALLOCATOR(FullResampler)
/**
 * @brief Stateful resampler wrapper over `src_new` + `src_process`.
 */
class MH_EUPH_API FullResampler {
private:
	std::unique_ptr< SRC_STATE, SrcStateDeleter > handleA;
	mutable SRC_DATA handleB;
	ChannelCount channels;
	ResampleType converterType;
	FullResampler( const FullResampler &cpy ) = delete;
	FullResampler& operator=( const FullResampler &cpy ) = delete;
public:
	/** @brief Destructor. */
	~FullResampler( );
	/**
	 * @brief Creates a stateful converter.
	 * @param channels Interleaved channel count.
	 * @param converterType Converter mode.
	 */
	explicit FullResampler( ChannelCount channels, ResampleType converterType =
										 ResampleType::SINC_FASTEST );
	/** @brief Move constructor. */
	FullResampler( FullResampler &&mov );
	/** @brief Move assignment. */
	FullResampler& operator=( FullResampler &&mov );
	/**
	 * @brief Resets internal converter state.
	 * @return libsamplerate error code (`0` on success).
	 */
	int reset( ) const;
	/**
	 * @brief Processes one conversion step using current `SRC_DATA`.
	 * @return libsamplerate error code (`0` on success).
	 */
	int process( ) const;
	/** @brief Returns the input data pointer currently stored in `SRC_DATA`. */
	const float *getDataIn( ) const;
	/** @brief Returns the output data pointer currently stored in `SRC_DATA`. */
	float *getDataOut( ) const;
	/** @brief Returns the input frame count currently stored in `SRC_DATA`. */
	FrameCount getInputFrames( ) const;
	/** @brief Returns the number of input frames consumed by the last process call. */
	FrameCount getInputFramesUsed( ) const;
	/** @brief Returns the output frame capacity currently stored in `SRC_DATA`. */
	FrameCount getOutputFrames( ) const;
	/** @brief Returns the number of output frames generated by the last process call. */
	FrameCount getOutputFramesGenerated( ) const;
	/** @brief Returns the current resampling ratio. */
	double getRatio( ) const;
	/** @brief Returns the end-of-input flag. */
	bool getEndOfInput( ) const;
	/** @brief Sets the input data pointer. */
	void setDataIn( const float *set_to ) const;
	/** @brief Sets the output data pointer. */
	void setDataOut( float *set_to ) const;
	/** @brief Sets the input frame count. */
	void setInputFrames( FrameCount set_to ) const;
	/** @brief Sets the output frame capacity. */
	void setOutputFrames( FrameCount set_to ) const;
	/** @brief Sets the resampling ratio. */
	void setRatio( double set_to ) const;
	/** @brief Sets the end-of-input flag. */
	void setEndOfInput( bool set_to ) const;
	/**
	 * @brief Sets the primary conversion parameters in one call.
	 * @param data_in Input interleaved float buffer.
	 * @param data_out Output interleaved float buffer.
	 * @param input_frames Number of available input frames.
	 * @param output_frames Maximum number of output frames.
	 * @param ratio Input-to-output sample-rate ratio.
	 */
	void set(const float *data_in, float *data_out, FrameCount input_frames,
			 FrameCount output_frames, double ratio ) const;

	/** @brief Returns the converter channel count. */
	ChannelCount getChannelCount( ) const;
	/** @brief Returns the converter type selected at construction. */
	ResampleType getResamplerType( ) const;
};

/**
 * @brief C-style callback signature expected by libsamplerate callback mode.
 *
 * The callback returns a frame count and sets `*data` to point at interleaved
 * sample data for those frames.
 */
typedef long ( *samplerate_callback )( void *cb_data, float **data );

/**
 * @brief Abstract interface used by callback-based resamplers.
 */
class CallbackInterfaceBase {
public:
	/** @brief Callback return payload: `(frames_available, sample_data_ptr)`. */
	typedef std::pair< long, float * > CallbackArgs;
	/** @brief Virtual destructor. */
	virtual ~CallbackInterfaceBase( ) = default;
	/**
	 * @brief Produces audio for callback-based resampling.
	 * @return `(frames_available, data_ptr)` pair.
	 */
	virtual CallbackArgs callBack( ) = 0;
};

DEFINE_CLASS_WITH_POLYMORPHIC_ALLOCATOR(CallbackResampler)
/**
 * @brief Wrapper over libsamplerate callback resampling API.
 */
class MH_EUPH_API CallbackResampler {
private:
	mutable int error;
	ResampleType converterType;
	std::unique_ptr< SRC_STATE, SrcStateDeleter > handle;
	ChannelCount channels;
	CallbackResampler( const CallbackResampler &cpy ) = delete;
	CallbackResampler& operator=( const CallbackResampler &cpy ) = delete;
public:
	/** @brief Virtual destructor. */
	virtual ~CallbackResampler();
	/** @brief Move constructor. */
	CallbackResampler( CallbackResampler &&mov );
	/** @brief Move assignment. */
	CallbackResampler& operator=( CallbackResampler &&mov );
	/**
	 * @brief Creates a callback resampler from a C-style callback function.
	 * @param func Callback invoked by libsamplerate to fetch source data.
	 * @param converter_type Converter mode.
	 * @param channels Interleaved channel count.
	 * @param userdata Opaque user data forwarded to `func`.
	 */
	CallbackResampler( samplerate_callback func,
					  ResampleType converter_type, ChannelCount channels,
					  void *userdata );
	/**
	 * @brief Creates a callback resampler from a C++ callback interface.
	 * @param interface Callback provider object.
	 * @param converter_type Converter mode.
	 * @param channels Interleaved channel count.
	 */
	CallbackResampler( CallbackInterfaceBase *interface,
					  ResampleType converter_type, ChannelCount channels );
	/**
	 * @brief Reads converted samples from callback mode.
	 * @param src_ratio Input-to-output sample-rate ratio.
	 * @param frames Requested output frame count.
	 * @param data Destination interleaved output buffer.
	 * @return Number of output frames written.
	 */
	FrameCount read( double src_ratio, FrameCount frames, float *data ) const;
	/**
	 * @brief Resets internal converter state.
	 * @return libsamplerate error code (`0` on success).
	 */
	int reset( ) const;
	/** @brief Returns the converter channel count. */
	ChannelCount getChannelCount( ) const;
	/** @brief Returns the converter type selected at construction. */
	ResampleType getResamplerType( ) const;
};

/**
 * @brief Convenience base class combining interface + callback resampler.
 *
 * Derive from this class and implement `callBack()` to provide source audio.
 */
class MH_EUPH_API CallbackInterface : public CallbackInterfaceBase,
									   public CallbackResampler {
public:
	/** @brief Virtual destructor. */
	virtual ~CallbackInterface( ) override = default;
	/**
	 * @brief Constructs a callback resampler bound to this object.
	 * @param channels Interleaved channel count.
	 * @param converter_type Converter mode.
	 */
	CallbackInterface(ChannelCount channels, ResampleType converter_type =
											 ResampleType::SINC_FASTEST );
	/** @brief Supplies source frames when callback mode requests them. */
	virtual CallbackArgs callBack( ) override = 0;
};

}
}
}

#endif // EUPHRESAMPLER_HPP
